### ISSUE TITLE
linebot: APIError 400 The property, 'to', in the request body is invalid (line: -, column: -)

### ISSUE THREAD

**Issue by windgo1019** [appleboy/drone-line#41]
I usw win10 and download drone-line-v1.4.0-windows-386.exe
When I get a secret and token
I use this command to start webhook
drone-line-v1.4.0-windows-386.exe --secret secret_key --token token_key webhook
then i use this command to send message

drone-line-v1.4.0-windows-386.exe --secret secret_key --token token_key --to windgo --message "test"
or 
drone-line-v1.4.0-windows-386.exe --secret secret_key --token token_key --to @nle4159v --message "test"

then i got a error mesage
"2016/12/19 11:21:57 linebot: APIError 400 The property, 'to', in the request body is invalid (line: -, column: -)"

could you give me a suggest?

**Comment by appleboy** [comment]
Your user ID is the wrong format. Please follows the following steps:

1. Setup webhook service.

```
drone-line-v1.4.0-windows-386.exe --secret secret_key --token token_key webhook
```

2. Add bot account to your friend list.

3. Send message to bot account

You can see the following screen shots to show `your personal ID`

![screen shot 2016-12-19 at 1 40 12 pm](https://cloud.githubusercontent.com/assets/21979/21302323/d9d05a98-c5f0-11e6-9b4d-3bd455b815cc.png)

Please Note `User ID` format.

4. Send message:

```
drone-line-v1.4.0-windows-386.exe --secret secret_key --token token_key --to U772346xxxxxxxx --message "test"
```
![screen shot 2016-12-19 at 1 45 37 pm](https://cloud.githubusercontent.com/assets/21979/21302400/84a53416-c5f1-11e6-8592-f0a517845d2d.png)

**Comment by appleboy** [comment]
@windgo1019 resolve your problem?

**Comment by windgo1019** [comment]
Thank for your reply!

I find the different point
I run the drone-line-v1.4.0-windows-386.exe then the program just stop in 
"Line Webhook Server Listin on 8088 port"
![image_20161227_013](https://cloud.githubusercontent.com/assets/19261696/21489138/112e7e98-cc22-11e6-8836-c1087f1ab580.png)

so I cant get the User ID to go next step
I try it in 2 PC ,drone-line-v1.4.0-windows-amd64.exe and drone-line-v1.4.0-windows-386.exe ,but i get the same result

below is my run command:
drone-line-v1.4.0-windows-amd64.exe --secret e27bfd26c58c279b24eebea7f23b69b3 --token HkCs4ouXy5x1FPxU5DrbMpLPH5Uz9rV6Ek9D8aHDLktos3SKr//V4pgi+H7ijV1MfBqLdIbhsJBwbQgtogr4aZRWyjv8tBjLi8SRTELG+2NmMu4ZVGOZLOE/3LRXUtolkZSE4kfRojR0XscLybJckAdB04t89/1O/w1cDnyilFU= webhook

**Comment by appleboy** [comment]
You are missing some steps. Please get User ID first.

After running webhook service. You need to run `ngrok` command as following:

```bash
$ ngrok http 8088
```

Then you will get ngrok URL and put it into Webhook URL field on Line developer admin console.

ref: https://blog.wu-boy.com/2016/11/send-line-notification-using-docker-written-in-golang/

**Comment by windgo1019** [comment]
Thank you!
I already message LineBot!

**Comment by appleboy** [comment]
Please close this issue if above solution is working for you.
